version: "3.8"
name: backend_oceanx

services:
  api:
    container_name: api_rest_node_oceanx
    restart: unless-stopped
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  phpmyadmin:
    container_name: php_my_admin_oceanx
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  db:
    container_name: db_mysql_oceanx
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: zKQdDQFTeG
      MYSQL_DATABASE: oceanx
    ports:
      - "3006:3006"